[package]
name = "yt-cipher"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
const_format = "0.2.34"
fancy-regex = "0.14.0"
regex = "1.11.1"
